# Generated by Django 2.2.7 on 2019-11-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrun',
            name='mass',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=99),
            preserve_default=False,
        ),
    ]
